services:
  php:
    build: .   # Dockerfileがdocker-compose.ymlと同じフォルダにあるのでここを指定
    container_name: app_php
    volumes:
      - .:/var/www/html/exam_app
    ports:
      - "8082:80"   # exam_app用ポート
    environment:
      DB_HOST: db
      DB_NAME: exam_app
      DB_USER: exam_user
      DB_PASS: exam_pass
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: exam_app_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: exam_app
      MYSQL_USER: exam_user
      MYSQL_PASSWORD: exam_pass
    ports:
      - "3307:3306"
    volumes:
      - kawab_exam_db_data:/var/lib/mysql
      - ./exam_app/src/exam_app/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - db

volumes:
  kawab_exam_db_data:
